version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - .:/workspace:cached
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    working_dir: /workspace
    command: bash -c "pip install --no-cache-dir --upgrade -r /workspace/requirements.txt && ./scripts/run.sh"
    ports:
      - 8000:8080
    env_file:
      - .env
      - .env.test
    depends_on:
      - mysql
    networks:
      - mock_network

  mysql:
    image: mysql:8.0
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mock_db
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mock_network
  mysql_test:
    image: mysql:8.0
    container_name: "mysql_test"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_mock_db
    env_file:
      - .env.test
    ports:
      - 3307:3306
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mock_network
  atlas:
    build:
      context: ./docker/atlas
      dockerfile: Dockerfile
    container_name: "atlas"
    volumes:
      - ./migrations:/migrations
      - ./atlas.hcl:/atlas.hcl
    command: ["tail", "-f", "/dev/null"]
    networks:
      - mock_network
  
networks:
  mock_network:
    name: mock_network
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mysql_test_data:
    driver: local